{
 "title": "Details",
 "time": { "from": "2020-01-18T07:21:00.624Z", "to": "2020-04-14T20:16:35.477Z" },
 "templating": {
  "list": [
   { "name": "country", "label": "select country", "query": "SELECT name FROM country" }
  ]
 },
 "panels": [
  {
   "title": "Confirmed Cases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as time, confirmed as \"Confirmed\"\nFROM country_details\nWHERE name = '$country' ;"
    }
   ]
  },
  {
   "title": "Death Cases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as time, deaths as \"Deaths\"\nFROM country_details\nWHERE name = '$country' ;"
    }
   ]
  },
  {
   "title": "Recovered Cases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as time, recovered as \"Recovered\"\nFROM country_details\nWHERE name = '$country' ;"
    }
   ]
  }
 ]
}